// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIoPnVe2zJ_9WvufTSaDsPztKxPgek0xM',
    appId: '1:345029820298:web:227a067cab0a9a5ef01273',
    messagingSenderId: '345029820298',
    projectId: 'moodku-cok',
    authDomain: 'moodku-cok.firebaseapp.com',
    storageBucket: 'moodku-cok.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGwLWsyUZYeB8ObLGJtMG9qsLnFepCnKk',
    appId: '1:345029820298:android:3b17026e04c05910f01273',
    messagingSenderId: '345029820298',
    projectId: 'moodku-cok',
    storageBucket: 'moodku-cok.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvsgW9OFFHl7KfkoofjMuZUcT-Al-aWd8',
    appId: '1:345029820298:ios:a04a379f014645d8f01273',
    messagingSenderId: '345029820298',
    projectId: 'moodku-cok',
    storageBucket: 'moodku-cok.appspot.com',
    iosClientId: '345029820298-9940oi9iug2134ir4a1e6cafhqvlm19i.apps.googleusercontent.com',
    iosBundleId: 'com.example.moodku',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvsgW9OFFHl7KfkoofjMuZUcT-Al-aWd8',
    appId: '1:345029820298:ios:77bf1535051855eaf01273',
    messagingSenderId: '345029820298',
    projectId: 'moodku-cok',
    storageBucket: 'moodku-cok.appspot.com',
    iosClientId: '345029820298-tk8fjt11la75qsogls8v3nm5keojfs7v.apps.googleusercontent.com',
    iosBundleId: 'com.example.moodku.RunnerTests',
  );
}
